<definitions name="service d\'authentification pour les sites du groupe acrobatt6" targetNamespace="http://localhost/auth_serv/wsdl/serv.wsdl"><!-- 
definition of datatypes -->
    <types>
        <schema targetNamespace="fr.accroauxbattes.authentificationserver.xsd">
            <element name="email">
                <complexType>
                    <all>
                        <element 
                            name="value" type="string"/>
                    </all>
                </complexType>
            </element>
            <element name="mdp">
                <complexType>
                    <all>
                        <element name="value" 
                                                                                                         type="string"/>
                    </all>
                </complexType>
            </element>
            <element name="result">
                <complexType>
                    <all>
                        <element name="value" 
                                                                                               type="string"/>
                    </all>
                </complexType>
            </element>
        </schema>
    </types><!-- response messages -->
    <message name="returns_result">
        <part name="result" 
                                                                                                                             type="xsd:result"/>
    </message><!-- request messages -->
    <message name="Check_Login">
        <part name="email" type="xsd:email"/>
        <part name="mdp" 
                                                                                                                             type="xsd:mdp"/>
    </message><!-- server's services -->
    <portType name="authentification server">
        <operation name="Check_Login">
            <input 
                message="tns:Check_Login"/>
            <output message="tns:returns_result"/>
        </operation>
    </portType><!-- server encoding -->
    <binding name="authentification 
server_webservices" type="tns:authentification server">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation 
            name="Check_Login">
            <soap:operation soapAction="urn:xmethods-delayed-quotes#Check_Login"/>
            <input>
                <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" 
                                                                                                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" 
                                                                                      encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding><!-- access to service provider -->
    <service name="acrobattgrp6">
        <port 
            name="acrobattgrp6_0" binding="authentification server_webservices">
            <soap:address 
                location="http://localhost/auth_serv/index.php"/>
        </port>
    </service>
</definitions>
